apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamedsameh2002/kubernetes-helm-retail-store.git
    targetRevision: main
    path: helm/ui-chart
    helm:
      valueFiles:
        - values-ui.yaml
    # ned checkr here to decide is values prodaction or dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true    # Auto-delete resources not in Git
      selfHeal: true # Auto-sync if drift detected
    syncOptions:
      - CreateNamespace=true