apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carts.configMapName" . }}
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: {{ .Values.app.persistence.provider }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: {{ .Values.app.persistence.dynamodb.tableName }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: {{ .Values.app.persistence.dynamodb.createTable | quote }}
  # RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: https://dynamodb.{{ .Values.app.persistence.dynamodb.region }}.amazonaws.com
  AWS_REGION: {{ .Values.app.persistence.dynamodb.region }}
  AWS_DEFAULT_REGION: {{ .Values.app.persistence.dynamodb.region }}

